const USER = {
  SET_USER: 'SET_USER'
}

const CART = {
  TOGGLE: 'TOGGLE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ONE_ITEM: 'REMOVE_ONE_ITEM',
  ADD_ONE_ITEM: 'ADD_ONE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM'
}

export { USER, CART }