const USER = {
  SET_USER: 'SET_USER'
}

const CART = {
  TOGGLE: 'TOGGLE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM'
}

const SHOP = {
  UPDATE_SHOP: 'UPDATE_SHOP'
}

const LOADING = {
  IS_LOADING: 'IS_LOADING'
}

export { USER, CART, SHOP, LOADING }