const USER = {
  SET_USER: 'SET_USER'
}

const CART = {
  TOGGLE: 'TOGGLE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM'
}

const SHOP = {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
}

export { USER, CART, SHOP }